# Generated by Django 4.2.1 on 2023-07-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='bill',
            field=models.BinaryField(),
        ),
    ]
