# Generated by Django 4.2.1 on 2023-07-29 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_fpgrowth_itemsets'),
    ]

    operations = [
        migrations.CreateModel(
            name='fpRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='fpgrowth',
            name='key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fpKey', to='home.fprecord'),
        ),
    ]
