# Generated by Django 4.2.1 on 2023-07-30 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_fprecord_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='associationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.fprecord')),
            ],
        ),
        migrations.CreateModel(
            name='association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedents', models.BinaryField()),
                ('consequents', models.BinaryField()),
                ('lift', models.FloatField()),
                ('confidence', models.FloatField()),
                ('support', models.FloatField()),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associationKey', to='home.associationrecord')),
            ],
        ),
    ]
