# Generated by Django 4.2.1 on 2023-07-30 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_associationrecord_association'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associationrecord',
            old_name='contact',
            new_name='fpKey',
        ),
    ]
